server:
  port: 8080
  servlet:
    context-path: /
    
spring:
  application:
    name: book-review-platform
  
  profiles:
    active: dev
  
  datasource:
    url: jdbc:h2:mem:bookreview
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    
  h2:
    console:
      enabled: true
      path: /h2-console
      
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        
  data:
    jpa:
      repositories:
        enabled: true

logging:
  level:
    com.bookreview: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      access-token-expiration: 86400000 # 24 hours
      refresh-token-expiration: 604800000 # 7 days
  
  # OpenAI Configuration (for future integration)
  openai:
    api-key: ${OPENAI_API_KEY:}
    enabled: ${OPENAI_ENABLED:false}
    model: gpt-3.5-turbo
    max-tokens: 150
    temperature: 0.7