-- This file ensures the user_favorite_books table is created correctly
-- Note: This is mainly for documentation as Hibernate will create the tables

-- The user_favorite_books table should be created by Hibernate with this structure:
-- CREATE TABLE user_favorite_books (
--     user_id BIGINT NOT NULL,
--     book_id BIGINT NOT NULL,
--     PRIMARY KEY (user_id, book_id),
--     FOREIGN KEY (user_id) REFERENCES users(id),
--     FOREIGN KEY (book_id) REFERENCES books(id)
-- );
